#!/bin/bash
sudo make install -C /home/por07g/Documents/Atlantis_codes/Hydroconstruct/HydroConstruct/HydroConstruct/trunk
if [ $? -eq 0 ] ; then
    #valgrind --leak-check=full --log-file=Valgrind.%p --show-reachable=yes
    #gdb --args
    /home/por07g/Documents/Atlantis_codes/Hydroconstruct/HydroConstruct/HydroConstruct/trunk/HydroConstruct -f flowout.cdf -t tempout.cdf -s saltout.cdf -r parameters.prm

    mkdir out_EAAM
    mv saltout.cdf  out_EAAM
    mv tempout.cdf  out_EAAM
    mv flowout.cdf  out_EAAM/flowout.cdf
    mv volume1.cdf  out_EAAM/volume.cdf

    cd  out_EAAM
    ncgen -o EAAM_temp.nc tempout.cdf
    ncgen -o EAAM_salt.nc saltout.cdf
    ncgen -o EAAM_hydro.nc flowout.cdf

    cd ..


else
    echo 'Failed to compile hydro construct'

fi
